name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Upgrade Deno
        run: deno upgrade

      - name: Install dependencies
        run: deno task cache

      - name: Run tests
        run: deno task test -A
